version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install
      - run:
          name: Update NPM
          command: npm install -g npm
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the site
          command: npm run build
      - run:
          name: Add asf.yaml file
          command: |
            echo "publish:" > ./out/.asf.yaml
            echo "  whoami: asf-site" >> ./out/.asf.yaml
      - run:
          name: Deploy to asf-site branch
          command: |
            cd out
            git init
            git config user.name "circleci"
            git config user.email "circleci@example.com"
            git add .
            git commit -m "Deploy to asf-site"
            git push --force https://${CIRCLE_TOKEN}@github.com/apache/incubator-resilientdb-site.git master:asf-site

workflows:
  build:
    jobs:
      - build
